# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fd0bb7cbd546e478f852f9ee16622afa852f0f4231710ade8bfa5850dc2adc97bee52314bb98ac4dc4fcc21f79c40b69d2cf5ee2f36cf09d9200ca234074da8

test:
  secret_key_base: f5047b7125d82f1f0f8e402eaa107af5053c70459570e35c48589615f7c70730312a54b7da835c2ca25ec09cc31db234019f000edd30e3a3adc5c9329deadb85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
